# Generated by Django 6.1.2 on 2026-10-09 02:09

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=20, verbose_name='ФН')),
                ('fd', models.CharField(max_length=20, verbose_name='ФД')),
                ('fp', models.CharField(max_length=20, verbose_name='ФП')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))], verbose_name='Сумма')),
                ('purchase_date', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='unique_fn_fd_fp_receipt')],
            },
        ),
    ]
